const text = {
    1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar quam ac tincidunt tincidunt. Sed dapibus mauris vel sem ultrices, ut volutpat ex gravida. Nulla facilisi. Morbi aliquam fermentum dui, ut volutpat libero dictum id. Proin ut odio et risus ullamcorper semper. Nam et libero vel tortor fermentum dictum. Nullam vehicula, urna non facilisis dapibus, justo eros venenatis eros, nec bibendum nisl dui vel justo. Quisque sit amet justo auctor, malesuada purus non, aliquam elit. Sed posuere risus in tincidunt pellentesque. Nunc scelerisque turpis vel nunc rhoncus malesuada. Cras fermentum, urna vel fermentum vestibulum, erat libero elementum ligula, eu venenatis libero orci a risus.",
    2: "Praesent bibendum, augue id tempus tristique, arcu mi ullamcorper elit, ut consectetur odio lectus nec lectus. Vivamus vitae est eget quam consectetur fermentum. Integer non hendrerit arcu. Nulla facilisi. Vestibulum efficitur est vel ex lacinia, eget vestibulum quam feugiat. Vestibulum hendrerit ac lectus sit amet sagittis. Duis euismod in libero a laoreet. Etiam eget orci ac tortor auctor bibendum id eget neque. Nunc ac leo et ipsum malesuada euismod. Curabitur id efficitur erat, et feugiat ex. Nulla nec velit neque.",
    3: "Cras vitae purus lectus. Vivamus sed mi quis odio fringilla dictum ut id quam. Sed at enim sed libero dignissim facilisis. Vestibulum vel odio ac tellus tincidunt lacinia. Sed varius urna id est tincidunt, ut malesuada quam mattis. Morbi pellentesque lectus eget mi facilisis, ut euismod tortor tempor. Sed non est a elit dictum blandit. Phasellus sed quam vel ligula fermentum convallis a ut libero. Nulla facilisi.",
    4: "In ut justo id libero lacinia hendrerit sit amet ac erat. Pellentesque vehicula viverra sapien nec interdum. Fusce suscipit euismod bibendum. Proin sit amet tristique quam. Maecenas scelerisque bibendum metus, nec bibendum odio iaculis ut. Vivamus eget velit et lectus sollicitudin scelerisque. Integer tincidunt erat id bibendum iaculis. Fusce varius ac libero at scelerisque. Duis sit amet nulla in turpis semper dictum a non felis. Fusce a libero euismod, sagittis massa ut, congue arcu.",
    5: "Nulla facilisi. Aliquam congue vel risus non vulputate. Curabitur fringilla elit eget libero hendrerit. Praesent a mauris eu mi vestibulum interdum. Etiam eu ligula id ipsum viverra bibendum in eget lectus. Suspendisse ac sapien ut massa ultricies mattis. Vivamus sit amet ante eu orci pellentesque laoreet vel in odio. Sed nec venenatis velit, et sagittis odio.",
    6: "Cras a luctus justo. Vestibulum in ex sit amet libero tincidunt auctor. Fusce ut est vel odio tincidunt eleifend nec vel quam. Sed ultrices, augue in cursus egestas, metus purus gravida dui, et tincidunt quam quam sit amet lorem. Nullam lacinia, nulla quis aliquam facilisis, eros quam malesuada neque, a dictum odio metus non justo. Aenean dictum, ipsum in sagittis facilisis, sapien odio fermentum dui, in fringilla dui mi nec leo. Curabitur quis tincidunt arcu. Sed viverra at nisl eu laoreet.",
    7: "Praesent vel urna vel libero luctus vestibulum id non augue. Nunc sit amet augue sit amet odio venenatis fermentum. Curabitur vitae ligula eget arcu interdum cursus. In auctor lectus ut enim sodales, et dictum libero laoreet. Nulla facilisi. Sed sit amet euismod turpis. Vestibulum tristique tincidunt orci vel convallis. Proin tincidunt nec velit quis interdum. Fusce scelerisque ac ex non ultricies.",
    8: "Cras sagittis justo nec lacus ullamcorper, et egestas justo tristique. Morbi id eros quis dolor laoreet ultricies. Nullam et vestibulum purus. Proin tristique vehicula odio nec aliquet. In consectetur, libero id dictum sagittis, mi elit tempus libero, vel mattis lectus sapien non tortor. Quisque tristique est ut dolor tristique tincidunt. Sed eget venenatis odio. Donec at libero congue.",
    9: "Vestibulum euismod nec quam in aliquet. In malesuada in turpis eget ullamcorper. Nulla facilisi. Sed auctor a orci eget aliquet. Nunc sed malesuada orci. Nullam eget aliquet lorem, a malesuada arcu. Sed tristique aliquet risus, at ultrices velit. Phasellus in justo vestibulum. Aliquam erat volutpat. Proin vitae hendrerit nulla.",
    10: "Suspendisse quis arcu id tortor tristique hendrerit ac sit amet lectus. Etiam vitae eleifend quam, a bibendum tellus. Aenean ac libero ac arcu vulputate egestas ac id purus. Curabitur laoreet vel quam vel congue. Sed id dolor id sapien facilisis accumsan. Nulla nec orci ligula. Proin sit amet libero mi."
  };
  