const text = {
  1: "On a quiet hill the wind whispered through the trees gently rustling leaves in a dance of nature birds soared in the open sky their wings painting streaks of freedom against the canvas of blue a babbling brook meandered through the meadow its crystal-clear waters reflecting the serenity of the surroundings in the distance mountains stood as silent sentinels their majestic peaks touching the heavens flowers bloomed adding vibrant splashes of color to the landscape amidst this symphony of sights and sounds time seemed to stand still creating a timeless moment where the beauty of the world unfolded in silent harmony",
  2: "Amidst the bustling city life buildings towered over crowded streets and cars moved in a chaotic ballet of motion Neon lights flickered casting a kaleidoscope of colors on the faces of hurried pedestrians Street vendors shouted offering a myriad of goods to passersby A distant hum of activity permeated the air creating an urban soundtrack In this vibrant cacophony each person moved with a purpose navigating the labyrinth of the metropolis The city like a living organism pulsed with energy telling tales of ambition dreams and the perpetual rhythm of life in an ever-evolving urban landscape",
  3: "Underneath the vast sky the meadow stretched endlessly a sea of grass swaying in the gentle breeze Trees stood sentinel along the horizon their leaves whispering secrets to the wind In the distance a river meandered its glistening waters reflecting the sunlight Birds circled above their wings a graceful ballet against the azure canvas Flowers painted the landscape with bursts of color nature's palette on full display As the day unfolded the meadow embraced the symphony of life a harmonious blend of sights and sounds that echoed the timeless rhythm of the natural world",
  4: "Within the ancient forest towering trees formed a cathedral of green their branches interlocking like the intricate arches of a grand sanctuary Sunlight filtered through the dense foliage creating a dappled mosaic on the forest floor In the open field a lone scarecrow stood guard its tattered clothes billowing in the wind A murder of crows circled above their dark silhouettes adding a touch of mystery to the rural tableau High above the mountain peaks an eagle soared its wings outstretched against the boundless sky The crisp mountain air carried whispers of solitude as if the very essence of the landscape whispered secrets to those who dared to listen ",
  5: "Through the concrete jungle people moved with purpose skyscrapers reaching for the sky in a testament to human ambition Cars weaved through the maze of streets their engines humming in a ceaseless urban symphony Neon signs flickered casting a vibrant glow on the faces of passersby Amidst the chaos each individual carried a story in their hurried steps a narrative written in the language of the city A tapestry of lives intertwined in the bustling metropolis creating a mosaic of dreams and aspirations amid the ceaseless flow of time and movement",
  6: "Amidst the towering skyscrapers the city heartbeat pulsed relentlessly People hurried through crowded streets faces obscured by the rush of urban life Horns blared in a symphony of impatience as cars navigated the labyrinth of asphalt and steel Neon signs flickered above a sea of humanity each individual a mere speck in the vastness of the metropolis Concrete and glass stretched endlessly creating a modern landscape that rose in defiance against the sky Yet within this chaos a quiet resilience prevailed a silent understanding that within the urban cacophony each person carved their own narrative",
  7: "In the twilight hours the city transformed into a tapestry of lights buildings stood tall casting long shadows on bustling streets Cars moved in a ceaseless stream their headlights cutting through the evening fog Neon signs blinked in a chaotic rhythm creating a kaleidoscope of colors against the urban backdrop Amidst the noise and chaos individuals hurried with a sense of purpose their silhouettes merging into the city's collective movement The night unfolded as a symphony of urban life where each person played a note in the grand composition of the metropolis",
  8: "By the riverbank tall grasses swayed in the gentle breeze dragonflies flitted above the water's surface a symphony of chirping crickets filled the air beneath the overarching trees a tranquil scene painted in shades of green and brown sunlight filtered through the foliage creating a play of shadows on the soft ground the river flowed steadily its rhythmic babbling harmonizing with the natural melody of the surroundings a haven of peace undisturbed by the external world a sanctuary where time seemed to suspend itself in a perpetual state of quiet contemplation",
  9: "Upon the rocky cliff overlooking the turbulent sea a solitary lighthouse stood tall its beacon piercing the darkness Waves crashed relentlessly against the jagged rocks their thunderous roars harmonizing with the rhythmic pulse of the beacon A storm brewed on the horizon dark clouds swirling ominously as if nature itself were staging a dramatic performance Yet within the stoic lighthouse a sense of calm pervaded the keeper diligently tending to the eternal dance of light and shadow A timeless saga unfolded in this maritime theater where the lighthouse stood as a steadfast guardian of the",
  10: "By the riverside a weeping willow stood tall its branches cascading like a veil around the water edge The river flowed gently carrying reflections of the surrounding nature A symphony of frogs and crickets serenaded the night creating a lullaby for the peaceful creatures that called the riverside home Amidst the stillness fireflies flickered like fleeting stars in the obsidian sky painting a mesmerizing dance of light and shadow The moon hung low casting a silvery glow on the scene turning the riverside into a tranquil dreamscape where time seemed to stand still"
};
